### ISSUE TITLE
Data Autoreply (Bug)

### ISSUE THREAD

**Issue by skeggse** [squaremo/node-spb#1]
Somehow it looks like `spb` automatically replies to its socket with the data it received. Or something. Node v0.10.20.

``` js
var net = require('net');
var spb = require('spb');

var server = net.createServer(function(conn) {
  var stream = spb.stream(conn);

  stream.write('hello', 'utf-8');
  stream.on('data', function(data) {
    console.log('server got', data.toString());
  });
});

server.listen(3000);

var socket = net.connect(3000);
var stream = spb.stream(socket);
```

If I run this example, I expect nothing to be printed out. In reality, it prints out `server got hello`. This is pretty counterintuitive because the client never sent `hello`, but the server did.

If we remove the last line, it works as expected, except I can't then use the client `stream`.

**Comment by squaremo** [comment]
Goodness me, this library is way out of date. It does all sorts of work it doesn't need to any more.

**Comment by skeggse** [comment]
Oh hey, didn't notice the `2 years ago` part. Mind if I try sprucing it up?

**Comment by squaremo** [comment]
Not at all, go for gold. I do wonder what the 'modern' approach would be. Possibly just wrappers for Readable, Writable, and Duplex streams.

**Comment by skeggse** [comment]
I took a first stab at it, but it starts to get weird because I don't want to sabotage the ability to use the stream as a pull stream.

``` js
function BlobStream(underlying) {
  Duplex.call(this);

  this._awaiting = 0;

  this._underlying = underlying;
  underlying.on('readable', readMore.bind(this));
  underlying.on('end', this.emit.bind(this, 'end'));
  underlying.on('close', this.emit.bind(this, 'close'));
  underlying.on('error', this.emit.bind(this, 'error'));
  underlying.on('drain', this.emit.bind(this, 'drain'));
  underlying.on('finish', this.emit.bind(this, 'finish'));
  underlying.on('pipe', this.emit.bind(this, 'pipe'));
  underlying.on('unpipe', this.emit.bind(this, 'unpipe'));
}

util.inherits(BlobStream, Duplex);

BlobStream.prototype._read = dataStart; // dataSize dataMore

BlobStream.prototype._write = function(data, encoding, callback) {
  var length = data.length, buffer;
  if (length < 128) {
    buffer = new Buffer(length + 1);
    buffer[0] = length;
    data.copy(buffer, 1);
  } else {
    buffer = new Buffer(length + 4);
    buffer[0] = length >>> 24;
    buffer[1] = (length >>> 16) & 0xff;
    buffer[2] = (length >>> 8) & 0xff;
    buffer[3] = length & 0xff;
    data.copy(buffer, 4);
  }
  this._underlying.write(buffer, callback);
};

BlobStream.prototype.end = function() {
  Duplex.prototype.end.apply(this, arguments);
  this._underlying.end.apply(this._underlying, arguments);
};

function readMore() {
  (this._read !== dataStart || this._awaiting) && this._read();
}

function dataStart() {
  var data = this._underlying.read(1);
  if (data === null)
    return;
  if (data[0] === 0xff) {
    this._read = dataSize;
  } else {
    this._awaiting = data[0];
    this._read = dataMore;
  }
  this._read();
}

function dataSize() {
  var data = this._underlying.read(4);
  if (data !== null) {
    this._awaiting = readsize(data, 1);
    this._read = dataMore;
    this._read();
  }
}

function dataMore() {
  var data;
  if (this._awaiting) {
    data = this._underlying.read(this._awaiting);
    if (data !== null) {
      this.push(data);
      this._awaiting = 0;
      this._read = dataStart;
      this._read();
    }
  }
}
```

I feel like trying to make `BlobStream` wrap an `underlying` stream might not be the way to go here. I've always ended up resorting to a plain `Transform` stream whenever I use Streams2 because I've never figured this out.

**Comment by squaremo** [comment]
> I don't want to sabotage the ability to use the stream as a pull stream.

Not sure what you mean here, I thought your approach above was more or less sound.

To be honest, I would probably discard entirely the original code, which to a large extent was working around the limitations of streams(1) and my own unfamiliarity with node.js, and start from scratch.

**Comment by skeggse** [comment]
I ended up giving up on this, for the most part, and switching to pull-stream.

**Comment by squaremo** [comment]
@skeggse Yep, fair enough. Ta for giving it a go
